#! /bin/bash

alias builddev='docker compose build dev' 
alias startdev='docker compose up -d dev'
alias attdev='docker exec -it nothing_project-dev-1 bash'
alias dcud='docker compose up -d'
alias dcd='docker compose down'

alias gits='git status'
alias gitau="git add -u"
alias gitc='git commit'
alias gitca='git commit --amend'
alias gitcan='git commit --amend --no-edit'
