services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./broker/mosquitto/config:/mosquitto/config
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: strong_password
  dev:
    build: .
    tty: true
    volumes:
      - ./client:/app/client
      - ./database:/app/database
      - ./run:/app/run
      - .vscode-server:/root/.vscode-server
  grphana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana
  json-server:
    image: clue/json-server
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./json-server/data:/data
volumes:
  grafanadata: