services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ${HOST_PROJECT_PWD}/broker/mosquitto/:/mosquitto/
    networks:
      - network1

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: strong_password
    networks:
      - network1

  dev:
    build: .
    tty: true
    environment:
      - HISTFILE=/root/.bash_history
    env_file:
      - .env
    volumes:
      - .:/app/
      - .vscode-server:/root/.vscode-server
      - ./.bash_history:/root/.bash_history
      - ./.bashrc:/root/.bashrc
      - /var/run/docker.sock:/var/run/docker.sock
<<<<<<< HEAD
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
=======
>>>>>>> refs/remotes/origin/master
    networks:
      - network1

  grphana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana

  json-server:
    image: clue/json-server
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./json-server/data:/data
volumes:
  grafanadata:

networks:
  network1:
    external: true
    name: nothing_project